#!/bin/bash

# run the ma-scrape-fixer on the authoratative json. 
# no pretty print option.
python3 cli.py  -m format -i ./json/items.json -t -g

# create tables && set up tables
python3 cli.py -m create -i ./json/fixed_bands.json