#!/bin/bash

# run the ma-scrape-fixer on the authoratative json. 
# no pretty print option.
python3 ./scripts/metal-archives-scrape-formatter.py -i ./json/items.json -t -g

# create tables && set up tables
python3 ./scripts/db-setup.py